# -*- coding: utf-8 -*-
"""activity_14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_EZ-phfTwF76pI0VVvZM8NQmPjwrDRPS
"""

import streamlit as st
 import pickle

st.title('Crop Prediction System')
 model=pickle.load(open('model.pkl','rb'))

col1,col2=st.columns(2)
 n=col1.number_input('Enter Nitrogen')
 p=col2.number_input('Enter Phosporus')
 k=col1.number_input('Enter Potassium')
 t=col2.number_input('Enter Temperature')
 h=col1.number_input('Enter Humidity')
 ph=col2.number_input('Enter PH')
 r=col1.number_input('Enter Rainfall')

if st.button('Predict'):
  data=[[n,p,k,t,h,hp,r]]
  result=model.predict(data)[0]
  st.success(result)